### 查询用户列表
GET http://localhost:8080/authors
Accept : application/json
Content-Type : application/json;charset=UTF-8

### 查询用户信息
GET http://localhost:8080/authors/15
Accept : application/json
Content-Type : application/json;charset=UTF-8

### 新增方法
POST http://localhost:8080/authors
Content-Type: application/json

{
    "user_id": "21",
    "real_name": "梁桂钊",
    "nick_name": "梁桂钊"
}

### 更新方法
PUT http://localhost:8080/authors/21
Content-Type: application/json

{
    "real_name" : "lianggzone",
    "nick_name": "lianggzone"
}


### 删除方法
DELETE http://localhost:8080/authors/21
Accept : application/json
Content-Type : application/json;charset=UTF-8

###